# Generated by Django 4.1.1 on 2023-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('order', models.TextField(verbose_name='Состав заказа')),
            ],
        ),
        migrations.CreateModel(
            name='shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название пары')),
                ('content', models.TextField(blank=True, verbose_name='Цена')),
                ('content1', models.TextField(blank=6, verbose_name='Артикул')),
            ],
        ),
    ]
